name: Infra + Deploy

on:
  push:
    branches:
      
  workflow_dispatch:
    inputs:
      env:
        description: "qa or prod"
        required: true
        default: "qa"

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

jobs:
  terraform:
    name: Terraform (infra)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.7

      - name: Create secrets.auto.tfvars
        run: |
          cat > secrets.auto.tfvars <<EOF
          aws_accounts = {
            frontend = {
              access_key    = "${{ secrets.AWS_FRONTEND_ACCESS_KEY }}"
              secret_key    = "${{ secrets.AWS_FRONTEND_SECRET_KEY }}"
              session_token = "${{ secrets.AWS_FRONTEND_SESSION_TOKEN }}"
            }
            ms_a = {
              access_key    = "${{ secrets.AWS_MS_A_ACCESS_KEY }}"
              secret_key    = "${{ secrets.AWS_MS_A_SECRET_KEY }}"
              session_token = "${{ secrets.AWS_MS_A_SESSION_TOKEN }}"
            }
            ms_b = {
              access_key    = "${{ secrets.AWS_MS_B_ACCESS_KEY }}"
              secret_key    = "${{ secrets.AWS_MS_B_SECRET_KEY }}"
              session_token = "${{ secrets.AWS_MS_B_SESSION_TOKEN }}"
            }
            databases = {
              access_key    = "${{ secrets.AWS_DB_ACCESS_KEY }}"
              secret_key    = "${{ secrets.AWS_DB_SECRET_KEY }}"
              session_token = "${{ secrets.AWS_DB_SESSION_TOKEN }}"
            }
            bastion = {
              access_key    = "${{ secrets.AWS_BASTION_ACCESS_KEY }}"
              secret_key    = "${{ secrets.AWS_BASTION_SECRET_KEY }}"
              session_token = "${{ secrets.AWS_BASTION_SESSION_TOKEN }}"
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.env }}.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/features' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/prod'
        run: terraform apply -auto-approve -var-file="${{ github.event.inputs.env }}.tfvars"

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve -var-file="${{ github.event.inputs.env }}.tfvars"
